# Server Configuration
server:
  port: 8282

# Spring Configuration
spring:
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 60000
    expiry: 30

# OMDb Configuration
omdb:
  url: https://www.omdbapi.com/
  key: 39175f73

# Log Configuration
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.baraka: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG